!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 1000
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 18, y: 0, z: 37.5}
      - !Vector3 {x: 18, y: 0, z: 37.5}
      - !Vector3 {x: 18, y: 0, z: 37.5}
      rotations: [0, 0, 0]
      sizes:
      - !Vector3 {x: 29, y: 1, z: 5}
      - !Vector3 {x: 29, y: 1, z: 5}
      - !Vector3 {x: 29, y: 1, z: 5}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 10, y: 0, z: 34} 
      - !Vector3 {x: 15, y: 0, z: 9.5}
      sizes:
      - !Vector3 { x: 15, y: 3, z: 2 }
      - !Vector3 { x: 5, y: 3, z: 2 }
      rotations: [0,0]